import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'hi' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

// Translation data structure
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'nav.home': 'Home',
    'nav.features': 'Features',
    'nav.howItWorks': 'How it works',
    'nav.weather': 'Weather',
    'nav.contact': 'Contact',
    'nav.tryRecommendation': 'Try Recommendation',
    
    // Hero
    'hero.badge': 'Smart Agriculture Solutions',
    'hero.title': 'Optimize Your',
    'hero.titleHighlight': 'Crop Yields',
    'hero.subtitle': 'with AI-Powered Insights',
    'hero.description': 'Get personalized crop recommendations based on your soil conditions, climate data, and local farming patterns. Maximize productivity while minimizing resource waste.',
    'hero.getRecommendation': 'Get Recommendation',
    'hero.learnMore': 'Learn More',
    'hero.stats.varieties': 'Crop Varieties',
    'hero.stats.accuracy': 'Accuracy Rate',
    'hero.stats.farmers': 'Farmers Helped',
    'hero.improvement': '+32% Yield',
    'hero.improvementSub': 'Average Improvement',
    
    // Crop Recommendation
    'crop.title': 'Crop Recommendation System',
    'crop.description': 'Get personalized crop recommendations based on your local conditions. Our algorithm analyzes soil pH, rainfall, temperature, and seasonal patterns to suggest the most suitable crops for your farm.',
    'crop.formTitle': 'Farm Details',
    'crop.formDescription': 'Enter your farm location and current growing conditions',
    'crop.location': 'Location',
    'crop.locationPlaceholder': 'e.g., Mumbai, Maharashtra',
    'crop.soilPH': 'Soil pH',
    'crop.rainfall': 'Rainfall (mm)',
    'crop.temperature': 'Temperature (°C)',
    'crop.season': 'Season',
    'crop.season.spring': 'Spring',
    'crop.season.summer': 'Summer',
    'crop.season.monsoon': 'Monsoon',
    'crop.season.winter': 'Winter',
    'crop.selectSeason': 'Select season',
    'crop.getRecommendations': 'Get Recommendations',
    'crop.analyzing': 'Analyzing...',
    'crop.recommendedCrops': 'Recommended Crops',
    'crop.exportCSV': 'Export CSV',
    'crop.fillForm': 'Fill in your farm details and click "Get Recommendations" to see suitable crops for your conditions.',
    'crop.sowingMonths': 'Sowing Months',
    'crop.whyThisCrop': 'Why this crop',
    'crop.match': 'Match',
    
    // Weather
    'weather.title': 'Weather Insights',
    'weather.description': 'Get real-time weather data and farming-specific insights to help you make informed decisions about irrigation, planting, and harvesting.',
    'weather.localWeather': 'Local Weather',
    'weather.localWeatherDesc': 'Enter your city to get current weather conditions and 5-day forecast',
    'weather.cityPlaceholder': 'Enter city name (e.g., Mumbai, Delhi, Bangalore)',
    'weather.getWeather': 'Get Weather',
    'weather.loading': 'Loading...',
    'weather.note': 'This is a demo widget with mock data. In production, this would integrate with a real weather API like OpenWeatherMap or AccuWeather.',
    'weather.currentWeather': 'Current Weather',
    'weather.temperature': 'Temperature',
    'weather.humidity': 'Humidity',
    'weather.wind': 'km/h Wind',
    'weather.visibility': 'km Visibility',
    'weather.farmingRecommendations': 'Farming Recommendations',
    'weather.farmingRecommendationsDesc': 'Weather-based advice for your farming activities',
    'weather.forecast': '5-Day Forecast',
    'weather.forecastDesc': 'Plan your farming activities with extended weather predictions',
    
    // Contact
    'contact.title': 'Get in Touch',
    'contact.description': 'Have questions about crop recommendations or need technical support? We\'re here to help you optimize your farming operations.',
    'contact.contactUs': 'Contact Us',
    'contact.contactUsDesc': 'Fill out the form below and we\'ll respond as soon as possible',
    'contact.fullName': 'Full Name',
    'contact.namePlaceholder': 'Your full name',
    'contact.emailAddress': 'Email Address',
    'contact.emailPlaceholder': 'your.email@example.com',
    'contact.subject': 'Subject',
    'contact.subjectPlaceholder': 'What can we help you with?',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Please describe your question or feedback in detail...',
    'contact.sendMessage': 'Send Message',
    'contact.sendingMessage': 'Sending Message...',
    'contact.thankYou': 'Thank You!',
    'contact.thankYouMessage': 'Your message has been sent successfully. We\'ll get back to you within 24 hours.',
    'contact.sendAnother': 'Send Another Message',
    'contact.note': 'This is a demo contact form. In production, this would integrate with a backend service to actually send emails or store messages.',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.description': 'Find answers to common questions about our crop recommendation system, soil analysis tools, and weather insights.',
    'faq.commonQuestions': 'Common Questions',
    'faq.commonQuestionsDesc': 'Click on any question below to see the detailed answer',
    
    // Footer
    'footer.description': 'Empowering farmers with AI-driven crop recommendations, soil analysis, and weather insights to optimize agricultural productivity and sustainability.',
    'footer.quickLinks': 'Quick Links',
    'footer.features': 'Features',
    'footer.contact': 'Contact',
    'footer.getSupport': 'Get Support',
    'footer.copyright': 'All rights reserved.',
    'footer.builtWith': 'Built with React, TypeScript, and Tailwind CSS',
    'footer.demoNotice': 'This is a demonstration application showcasing frontend-only crop recommendation features. In production, this would integrate with real agricultural databases, weather APIs, and machine learning models for accurate, real-time recommendations.',
    
    // How It Works
    'howItWorks.title': 'How It Works',
    'howItWorks.description': 'Our intelligent crop recommendation system uses a data-driven approach to suggest the most suitable crops for your specific farming conditions.',
    'howItWorks.step': 'Step',
    'howItWorks.learnMore': 'Learn More',
    'howItWorks.inputDetails': 'Input Farm Details',
    'howItWorks.inputDetailsDesc': 'Provide your location and current growing conditions',
    'howItWorks.algorithmAnalysis': 'Algorithm Analysis',
    'howItWorks.algorithmAnalysisDesc': 'Our system analyzes your data against crop requirements',
    'howItWorks.scoring': 'Scoring & Ranking',
    'howItWorks.scoringDesc': 'Crops are scored and ranked based on suitability',
    'howItWorks.getRecommendations': 'Get Recommendations',
    'howItWorks.getRecommendationsDesc': 'Receive personalized crop suggestions with confidence scores',
    
    // Fertilizer
    'fertilizer.title': 'Soil Analysis & Fertilizer Recommendations',
    'fertilizer.description': 'Get detailed insights into your soil health and personalized fertilizer recommendations to optimize crop nutrition and maximize yields.',
    'fertilizer.basicView': 'Basic View',
    'fertilizer.advancedView': 'Advanced View',
    'fertilizer.soilHealth': 'Soil Health Overview',
    'fertilizer.soilHealthDesc': 'Current nutrient levels in your soil based on recent analysis',
    'fertilizer.nitrogen': 'Nitrogen (N)',
    'fertilizer.phosphorus': 'Phosphorus (P)',
    'fertilizer.potassium': 'Potassium (K)',
    'fertilizer.high': 'High',
    'fertilizer.medium': 'Medium',
    'fertilizer.low': 'Low',
    'fertilizer.optimal': 'Optimal levels',
    'fertilizer.adequate': 'Adequate levels',
    'fertilizer.needsImprovement': 'Needs improvement',
    
    // Common
    'common.required': 'is required',
    'common.invalidEmail': 'Please enter a valid email address',
    'common.invalidRange': 'must be between',
    'common.and': 'and',
    'common.minimum': 'Minimum',
    'common.characters': 'characters',
    'common.fixErrors': 'Please fix the form errors and try again',
    'common.loading': 'Loading...',
    'common.success': 'Success!',
    'common.error': 'Error',
    
    // Popup Translations
    // Welcome Popup
    'welcomeTitle': 'Welcome to AgriSmart!',
    'welcomeSubtitle': 'Your comprehensive agricultural intelligence platform',
    'cropRecommendation': 'Crop Recommendations',
    'welcomeFeature1': 'AI-powered suggestions for optimal crop selection based on your conditions',
    'weatherForecasting': 'Weather Insights',
    'welcomeFeature2': 'Real-time weather data and farming-specific recommendations',
    'soilAnalysis': 'Soil Analysis',
    'welcomeFeature3': 'Detailed soil health reports and fertilizer recommendations',
    'getStarted': 'Get Started',
    
    // Daily Tips Popup
    'dailyTip': 'Daily Agricultural Tip',
    'soilHealth': 'Soil Health',
    'tip1Title': 'Test Your Soil pH Regularly',
    'tip1Content': 'Soil pH affects nutrient availability. Most crops thrive in slightly acidic to neutral soil (pH 6.0-7.0). Test your soil every 2-3 years and adjust with lime or sulfur as needed.',
    'waterManagement': 'Water Management',
    'tip2Title': 'Implement Drip Irrigation',
    'tip2Content': 'Drip irrigation can reduce water usage by 30-50% while improving crop yields. It delivers water directly to plant roots, reducing evaporation and weed growth.',
    'pestControl': 'Pest Control',
    'tip3Title': 'Use Integrated Pest Management',
    'tip3Content': 'Combine biological, cultural, and chemical controls for effective pest management. Monitor pest populations regularly and use targeted treatments to minimize environmental impact.',
    'previous': 'Previous',
    'next': 'Next',
    
    // Location Permission Popup
    'locationPermissionTitle': 'Enable Location Access',
    'locationPermissionDescription': 'Allow us to access your location for personalized agricultural insights and local weather data.',
    'locationPrivacyNote': 'Your location data is only used to provide localized recommendations and is never shared with third parties.',
    'accurateWeather': 'Accurate Weather Data',
    'locationBenefit1': 'Get precise local weather forecasts and alerts',
    'localConditions': 'Local Growing Conditions',
    'locationBenefit2': 'Receive recommendations tailored to your specific region',
    'nearbyResources': 'Nearby Resources',
    'locationBenefit3': 'Find local suppliers, extension services, and markets',
    'skipForNow': 'Skip for Now',
    'allowLocation': 'Allow Location',
    'locationAccessGranted': 'Location access granted! You\'ll now receive personalized local recommendations.',
    'locationAccessDenied': 'Location access denied. You can still use all features with manual location entry.',
    
    // Newsletter Popup
    'newsletterTitle': 'Stay Updated',
    'newsletterDescription': 'Subscribe to our newsletter for the latest agricultural insights, seasonal tips, and crop recommendations.',
    'exclusiveBenefits': 'What you\'ll receive:',
    'seasonalTips': 'Weekly seasonal farming tips',
    'cropAlerts': 'Crop disease and pest alerts',
    'expertAdvice': 'Expert agricultural advice',
    'emailPlaceholder': 'Enter your email address',
    'noThanks': 'No Thanks',
    'subscribe': 'Subscribe',
    'subscribing': 'Subscribing...',
    'unsubscribeAnytime': 'You can unsubscribe at any time. We respect your privacy.',
    'validEmailRequired': 'Please enter a valid email address',
    'newsletterSubscribed': 'Successfully subscribed to our newsletter!',
  },
  
  es: {
    // Header
    'nav.home': 'Inicio',
    'nav.features': 'Características',
    'nav.howItWorks': 'Cómo funciona',
    'nav.weather': 'Clima',
    'nav.contact': 'Contacto',
    'nav.tryRecommendation': 'Probar Recomendación',
    
    // Hero
    'hero.badge': 'Soluciones de Agricultura Inteligente',
    'hero.title': 'Optimiza tu',
    'hero.titleHighlight': 'Rendimiento de Cultivos',
    'hero.subtitle': 'con Insights Potenciados por IA',
    'hero.description': 'Obtén recomendaciones personalizadas de cultivos basadas en las condiciones de tu suelo, datos climáticos y patrones agrícolas locales. Maximiza la productividad mientras minimizas el desperdicio de recursos.',
    'hero.getRecommendation': 'Obtener Recomendación',
    'hero.learnMore': 'Aprender Más',
    'hero.stats.varieties': 'Variedades de Cultivos',
    'hero.stats.accuracy': 'Tasa de Precisión',
    'hero.stats.farmers': 'Agricultores Ayudados',
    'hero.improvement': '+32% Rendimiento',
    'hero.improvementSub': 'Mejora Promedio',
    
    // Crop Recommendation
    'crop.title': 'Sistema de Recomendación de Cultivos',
    'crop.description': 'Obtén recomendaciones personalizadas de cultivos basadas en tus condiciones locales. Nuestro algoritmo analiza el pH del suelo, la lluvia, la temperatura y los patrones estacionales para sugerir los cultivos más adecuados para tu granja.',
    'crop.formTitle': 'Detalles de la Granja',
    'crop.formDescription': 'Ingresa la ubicación de tu granja y las condiciones de cultivo actuales',
    'crop.location': 'Ubicación',
    'crop.locationPlaceholder': 'ej., Madrid, España',
    'crop.soilPH': 'pH del Suelo',
    'crop.rainfall': 'Precipitación (mm)',
    'crop.temperature': 'Temperatura (°C)',
    'crop.season': 'Temporada',
    'crop.season.spring': 'Primavera',
    'crop.season.summer': 'Verano',
    'crop.season.monsoon': 'Monzón',
    'crop.season.winter': 'Invierno',
    'crop.selectSeason': 'Seleccionar temporada',
    'crop.getRecommendations': 'Obtener Recomendaciones',
    'crop.analyzing': 'Analizando...',
    'crop.recommendedCrops': 'Cultivos Recomendados',
    'crop.exportCSV': 'Exportar CSV',
    'crop.fillForm': 'Completa los detalles de tu granja y haz clic en "Obtener Recomendaciones" para ver los cultivos adecuados para tus condiciones.',
    'crop.sowingMonths': 'Meses de Siembra',
    'crop.whyThisCrop': 'Por qué este cultivo',
    'crop.match': 'Coincidencia',
    
    // Weather
    'weather.title': 'Información del Clima',
    'weather.description': 'Obtén datos meteorológicos en tiempo real e información específica para la agricultura para ayudarte a tomar decisiones informadas sobre riego, siembra y cosecha.',
    'weather.localWeather': 'Clima Local',
    'weather.localWeatherDesc': 'Ingresa tu ciudad para obtener las condiciones meteorológicas actuales y el pronóstico de 5 días',
    'weather.cityPlaceholder': 'Ingresa el nombre de la ciudad (ej., Madrid, Barcelona, Valencia)',
    'weather.getWeather': 'Obtener Clima',
    'weather.loading': 'Cargando...',
    'weather.note': 'Este es un widget de demostración con datos simulados. En producción, esto se integraría con una API meteorológica real como OpenWeatherMap o AccuWeather.',
    'weather.currentWeather': 'Clima Actual',
    'weather.temperature': 'Temperatura',
    'weather.humidity': 'Humedad',
    'weather.wind': 'km/h Viento',
    'weather.visibility': 'km Visibilidad',
    'weather.farmingRecommendations': 'Recomendaciones Agrícolas',
    'weather.farmingRecommendationsDesc': 'Consejos basados en el clima para tus actividades agrícolas',
    'weather.forecast': 'Pronóstico de 5 Días',
    'weather.forecastDesc': 'Planifica tus actividades agrícolas con predicciones meteorológicas extendidas',
    
    // Contact
    'contact.title': 'Ponte en Contacto',
    'contact.description': '¿Tienes preguntas sobre recomendaciones de cultivos o necesitas soporte técnico? Estamos aquí para ayudarte a optimizar tus operaciones agrícolas.',
    'contact.contactUs': 'Contáctanos',
    'contact.contactUsDesc': 'Completa el formulario a continuación y responderemos lo antes posible',
    'contact.fullName': 'Nombre Completo',
    'contact.namePlaceholder': 'Tu nombre completo',
    'contact.emailAddress': 'Dirección de Email',
    'contact.emailPlaceholder': 'tu.email@ejemplo.com',
    'contact.subject': 'Asunto',
    'contact.subjectPlaceholder': '¿En qué podemos ayudarte?',
    'contact.message': 'Mensaje',
    'contact.messagePlaceholder': 'Por favor describe tu pregunta o comentario en detalle...',
    'contact.sendMessage': 'Enviar Mensaje',
    'contact.sendingMessage': 'Enviando Mensaje...',
    'contact.thankYou': '¡Gracias!',
    'contact.thankYouMessage': 'Tu mensaje ha sido enviado exitosamente. Te responderemos dentro de 24 horas.',
    'contact.sendAnother': 'Enviar Otro Mensaje',
    'contact.note': 'Este es un formulario de contacto de demostración. En producción, esto se integraría con un servicio backend para enviar emails o almacenar mensajes.',
    
    // FAQ
    'faq.title': 'Preguntas Frecuentes',
    'faq.description': 'Encuentra respuestas a preguntas comunes sobre nuestro sistema de recomendación de cultivos, herramientas de análisis de suelo e información del clima.',
    'faq.commonQuestions': 'Preguntas Comunes',
    'faq.commonQuestionsDesc': 'Haz clic en cualquier pregunta a continuación para ver la respuesta detallada',
    
    // Footer
    'footer.description': 'Empoderando a los agricultores con recomendaciones de cultivos impulsadas por IA, análisis de suelo e información del clima para optimizar la productividad y sostenibilidad agrícola.',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.features': 'Características',
    'footer.contact': 'Contacto',
    'footer.getSupport': 'Obtener Soporte',
    'footer.copyright': 'Todos los derechos reservados.',
    'footer.builtWith': 'Construido con React, TypeScript y Tailwind CSS',
    'footer.demoNotice': 'Esta es una aplicación de demostración que muestra características de recomendación de cultivos solo frontend. En producción, esto se integraría con bases de datos agrícolas reales, APIs meteorológicas y modelos de aprendizaje automático para recomendaciones precisas y en tiempo real.',
    
    // How It Works
    'howItWorks.title': 'Cómo Funciona',
    'howItWorks.description': 'Nuestro sistema inteligente de recomendación de cultivos usa un enfoque basado en datos para sugerir los cultivos más adecuados para tus condiciones agrícolas específicas.',
    'howItWorks.step': 'Paso',
    'howItWorks.learnMore': 'Aprender Más',
    'howItWorks.inputDetails': 'Ingresar Detalles de la Granja',
    'howItWorks.inputDetailsDesc': 'Proporciona tu ubicación y condiciones de cultivo actuales',
    'howItWorks.algorithmAnalysis': 'Análisis del Algoritmo',
    'howItWorks.algorithmAnalysisDesc': 'Nuestro sistema analiza tus datos contra los requisitos de los cultivos',
    'howItWorks.scoring': 'Puntuación y Clasificación',
    'howItWorks.scoringDesc': 'Los cultivos son puntuados y clasificados basándose en la idoneidad',
    'howItWorks.getRecommendations': 'Obtener Recomendaciones',
    'howItWorks.getRecommendationsDesc': 'Recibe sugerencias personalizadas de cultivos con puntuaciones de confianza',
    
    // Fertilizer
    'fertilizer.title': 'Análisis de Suelo y Recomendaciones de Fertilizantes',
    'fertilizer.description': 'Obtén información detallada sobre la salud de tu suelo y recomendaciones personalizadas de fertilizantes para optimizar la nutrición de los cultivos y maximizar los rendimientos.',
    'fertilizer.basicView': 'Vista Básica',
    'fertilizer.advancedView': 'Vista Avanzada',
    'fertilizer.soilHealth': 'Resumen de Salud del Suelo',
    'fertilizer.soilHealthDesc': 'Niveles actuales de nutrientes en tu suelo basados en análisis recientes',
    'fertilizer.nitrogen': 'Nitrógeno (N)',
    'fertilizer.phosphorus': 'Fósforo (P)',
    'fertilizer.potassium': 'Potasio (K)',
    'fertilizer.high': 'Alto',
    'fertilizer.medium': 'Medio',
    'fertilizer.low': 'Bajo',
    'fertilizer.optimal': 'Niveles óptimos',
    'fertilizer.adequate': 'Niveles adecuados',
    'fertilizer.needsImprovement': 'Necesita mejora',
    
    // Common
    'common.required': 'es requerido',
    'common.invalidEmail': 'Por favor ingresa una dirección de email válida',
    'common.invalidRange': 'debe estar entre',
    'common.and': 'y',
    'common.minimum': 'Mínimo',
    'common.characters': 'caracteres',
    'common.fixErrors': 'Por favor corrige los errores del formulario e intenta de nuevo',
    'common.loading': 'Cargando...',
    'common.success': '¡Éxito!',
    'common.error': 'Error',
    
    // Popup Translations
    // Welcome Popup
    'welcomeTitle': '¡Bienvenido a AgriSmart!',
    'welcomeSubtitle': 'Tu plataforma integral de inteligencia agrícola',
    'cropRecommendation': 'Recomendaciones de Cultivos',
    'welcomeFeature1': 'Sugerencias impulsadas por IA para una selección óptima de cultivos basada en tus condiciones',
    'weatherForecasting': 'Información del Clima',
    'welcomeFeature2': 'Datos meteorológicos en tiempo real y recomendaciones específicas para la agricultura',
    'soilAnalysis': 'Análisis de Suelo',
    'welcomeFeature3': 'Informes detallados de salud del suelo y recomendaciones de fertilizantes',
    'getStarted': 'Comenzar',
    
    // Daily Tips Popup
    'dailyTip': 'Consejo Agrícola Diario',
    'soilHealth': 'Salud del Suelo',
    'tip1Title': 'Prueba el pH de tu Suelo Regularmente',
    'tip1Content': 'El pH del suelo afecta la disponibilidad de nutrientes. La mayoría de los cultivos prosperan en suelo ligeramente ácido a neutro (pH 6.0-7.0). Prueba tu suelo cada 2-3 años y ajusta con cal o azufre según sea necesario.',
    'waterManagement': 'Gestión del Agua',
    'tip2Title': 'Implementa Riego por Goteo',
    'tip2Content': 'El riego por goteo puede reducir el uso de agua en un 30-50% mientras mejora los rendimientos de los cultivos. Entrega agua directamente a las raíces de las plantas, reduciendo la evaporación y el crecimiento de malezas.',
    'pestControl': 'Control de Plagas',
    'tip3Title': 'Usa Manejo Integrado de Plagas',
    'tip3Content': 'Combina controles biológicos, culturales y químicos para un manejo efectivo de plagas. Monitorea las poblaciones de plagas regularmente y usa tratamientos dirigidos para minimizar el impacto ambiental.',
    'previous': 'Anterior',
    'next': 'Siguiente',
    
    // Location Permission Popup
    'locationPermissionTitle': 'Habilitar Acceso a Ubicación',
    'locationPermissionDescription': 'Permítenos acceder a tu ubicación para obtener información agrícola personalizada y datos meteorológicos locales.',
    'locationPrivacyNote': 'Tus datos de ubicación solo se usan para proporcionar recomendaciones localizadas y nunca se comparten con terceros.',
    'accurateWeather': 'Datos Meteorológicos Precisos',
    'locationBenefit1': 'Obtén pronósticos meteorológicos locales precisos y alertas',
    'localConditions': 'Condiciones de Cultivo Locales',
    'locationBenefit2': 'Recibe recomendaciones adaptadas a tu región específica',
    'nearbyResources': 'Recursos Cercanos',
    'locationBenefit3': 'Encuentra proveedores locales, servicios de extensión y mercados',
    'skipForNow': 'Omitir por Ahora',
    'allowLocation': 'Permitir Ubicación',
    'locationAccessGranted': '¡Acceso a ubicación concedido! Ahora recibirás recomendaciones locales personalizadas.',
    'locationAccessDenied': 'Acceso a ubicación denegado. Aún puedes usar todas las funciones con entrada manual de ubicación.',
    
    // Newsletter Popup
    'newsletterTitle': 'Mantente Actualizado',
    'newsletterDescription': 'Suscríbete a nuestro boletín para obtener las últimas perspectivas agrícolas, consejos estacionales y recomendaciones de cultivos.',
    'exclusiveBenefits': 'Lo que recibirás:',
    'seasonalTips': 'Consejos de cultivo semanales estacionales',
    'cropAlerts': 'Alertas de enfermedades y plagas de cultivos',
    'expertAdvice': 'Consejos agrícolas expertos',
    'emailPlaceholder': 'Ingresa tu dirección de email',
    'noThanks': 'No Gracias',
    'subscribe': 'Suscribirse',
    'subscribing': 'Suscribiendo...',
    'unsubscribeAnytime': 'Puedes cancelar la suscripción en cualquier momento. Respetamos tu privacidad.',
    'validEmailRequired': 'Por favor ingresa una dirección de email válida',
    'newsletterSubscribed': '¡Te has suscrito exitosamente a nuestro boletín!',
  },
  
  fr: {
    // Header
    'nav.home': 'Accueil',
    'nav.features': 'Fonctionnalités',
    'nav.howItWorks': 'Comment ça marche',
    'nav.weather': 'Météo',
    'nav.contact': 'Contact',
    'nav.tryRecommendation': 'Essayer la Recommandation',
    
    // Hero
    'hero.badge': 'Solutions d\'Agriculture Intelligente',
    'hero.title': 'Optimisez vos',
    'hero.titleHighlight': 'Rendements de Cultures',
    'hero.subtitle': 'avec des Insights Alimentés par l\'IA',
    'hero.description': 'Obtenez des recommandations de cultures personnalisées basées sur les conditions de votre sol, les données climatiques et les modèles agricoles locaux. Maximisez la productivité tout en minimisant le gaspillage des ressources.',
    'hero.getRecommendation': 'Obtenir une Recommandation',
    'hero.learnMore': 'En Savoir Plus',
    'hero.stats.varieties': 'Variétés de Cultures',
    'hero.stats.accuracy': 'Taux de Précision',
    'hero.stats.farmers': 'Agriculteurs Aidés',
    'hero.improvement': '+32% Rendement',
    'hero.improvementSub': 'Amélioration Moyenne',
    
    // Crop Recommendation
    'crop.title': 'Système de Recommandation de Cultures',
    'crop.description': 'Obtenez des recommandations de cultures personnalisées basées sur vos conditions locales. Notre algorithme analyse le pH du sol, les précipitations, la température et les modèles saisonniers pour suggérer les cultures les plus adaptées à votre ferme.',
    'crop.formTitle': 'Détails de la Ferme',
    'crop.formDescription': 'Entrez l\'emplacement de votre ferme et les conditions de culture actuelles',
    'crop.location': 'Emplacement',
    'crop.locationPlaceholder': 'ex., Paris, France',
    'crop.soilPH': 'pH du Sol',
    'crop.rainfall': 'Précipitations (mm)',
    'crop.temperature': 'Température (°C)',
    'crop.season': 'Saison',
    'crop.season.spring': 'Printemps',
    'crop.season.summer': 'Été',
    'crop.season.monsoon': 'Mousson',
    'crop.season.winter': 'Hiver',
    'crop.selectSeason': 'Sélectionner la saison',
    'crop.getRecommendations': 'Obtenir des Recommandations',
    'crop.analyzing': 'Analyse en cours...',
    'crop.recommendedCrops': 'Cultures Recommandées',
    'crop.exportCSV': 'Exporter CSV',
    'crop.fillForm': 'Remplissez les détails de votre ferme et cliquez sur "Obtenir des Recommandations" pour voir les cultures adaptées à vos conditions.',
    'crop.sowingMonths': 'Mois de Semis',
    'crop.whyThisCrop': 'Pourquoi cette culture',
    'crop.match': 'Correspondance',
    
    // Weather
    'weather.title': 'Informations Météorologiques',
    'weather.description': 'Obtenez des données météorologiques en temps réel et des informations spécifiques à l\'agriculture pour vous aider à prendre des décisions éclairées sur l\'irrigation, la plantation et la récolte.',
    'weather.localWeather': 'Météo Locale',
    'weather.localWeatherDesc': 'Entrez votre ville pour obtenir les conditions météorologiques actuelles et les prévisions sur 5 jours',
    'weather.cityPlaceholder': 'Entrez le nom de la ville (ex., Paris, Lyon, Marseille)',
    'weather.getWeather': 'Obtenir la Météo',
    'weather.loading': 'Chargement...',
    'weather.note': 'Ceci est un widget de démonstration avec des données simulées. En production, cela s\'intégrerait avec une vraie API météo comme OpenWeatherMap ou AccuWeather.',
    'weather.currentWeather': 'Météo Actuelle',
    'weather.temperature': 'Température',
    'weather.humidity': 'Humidité',
    'weather.wind': 'km/h Vent',
    'weather.visibility': 'km Visibilité',
    'weather.farmingRecommendations': 'Recommandations Agricoles',
    'weather.farmingRecommendationsDesc': 'Conseils basés sur la météo pour vos activités agricoles',
    'weather.forecast': 'Prévisions sur 5 Jours',
    'weather.forecastDesc': 'Planifiez vos activités agricoles avec des prédictions météorologiques étendues',
    
    // Contact
    'contact.title': 'Nous Contacter',
    'contact.description': 'Vous avez des questions sur les recommandations de cultures ou besoin d\'un support technique ? Nous sommes là pour vous aider à optimiser vos opérations agricoles.',
    'contact.contactUs': 'Nous Contacter',
    'contact.contactUsDesc': 'Remplissez le formulaire ci-dessous et nous répondrons dès que possible',
    'contact.fullName': 'Nom Complet',
    'contact.namePlaceholder': 'Votre nom complet',
    'contact.emailAddress': 'Adresse Email',
    'contact.emailPlaceholder': 'votre.email@exemple.com',
    'contact.subject': 'Sujet',
    'contact.subjectPlaceholder': 'Comment pouvons-nous vous aider ?',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Veuillez décrire votre question ou commentaire en détail...',
    'contact.sendMessage': 'Envoyer le Message',
    'contact.sendingMessage': 'Envoi du Message...',
    'contact.thankYou': 'Merci !',
    'contact.thankYouMessage': 'Votre message a été envoyé avec succès. Nous vous répondrons dans les 24 heures.',
    'contact.sendAnother': 'Envoyer un Autre Message',
    'contact.note': 'Ceci est un formulaire de contact de démonstration. En production, cela s\'intégrerait avec un service backend pour envoyer des emails ou stocker des messages.',
    
    // FAQ
    'faq.title': 'Questions Fréquemment Posées',
    'faq.description': 'Trouvez des réponses aux questions courantes sur notre système de recommandation de cultures, les outils d\'analyse du sol et les informations météorologiques.',
    'faq.commonQuestions': 'Questions Courantes',
    'faq.commonQuestionsDesc': 'Cliquez sur n\'importe quelle question ci-dessous pour voir la réponse détaillée',
    
    // Footer
    'footer.description': 'Autonomiser les agriculteurs avec des recommandations de cultures alimentées par l\'IA, l\'analyse du sol et les informations météorologiques pour optimiser la productivité et la durabilité agricoles.',
    'footer.quickLinks': 'Liens Rapides',
    'footer.features': 'Fonctionnalités',
    'footer.contact': 'Contact',
    'footer.getSupport': 'Obtenir du Support',
    'footer.copyright': 'Tous droits réservés.',
    'footer.builtWith': 'Construit avec React, TypeScript et Tailwind CSS',
    'footer.demoNotice': 'Ceci est une application de démonstration présentant des fonctionnalités de recommandation de cultures frontend uniquement. En production, cela s\'intégrerait avec de vraies bases de données agricoles, des APIs météo et des modèles d\'apprentissage automatique pour des recommandations précises et en temps réel.',
    
    // How It Works
    'howItWorks.title': 'Comment Ça Marche',
    'howItWorks.description': 'Notre système intelligent de recommandation de cultures utilise une approche basée sur les données pour suggérer les cultures les plus adaptées à vos conditions agricoles spécifiques.',
    'howItWorks.step': 'Étape',
    'howItWorks.learnMore': 'En Savoir Plus',
    'howItWorks.inputDetails': 'Saisir les Détails de la Ferme',
    'howItWorks.inputDetailsDesc': 'Fournissez votre emplacement et les conditions de culture actuelles',
    'howItWorks.algorithmAnalysis': 'Analyse de l\'Algorithme',
    'howItWorks.algorithmAnalysisDesc': 'Notre système analyse vos données par rapport aux exigences des cultures',
    'howItWorks.scoring': 'Notation et Classement',
    'howItWorks.scoringDesc': 'Les cultures sont notées et classées en fonction de leur adéquation',
    'howItWorks.getRecommendations': 'Obtenir des Recommandations',
    'howItWorks.getRecommendationsDesc': 'Recevez des suggestions de cultures personnalisées avec des scores de confiance',
    
    // Fertilizer
    'fertilizer.title': 'Analyse du Sol et Recommandations d\'Engrais',
    'fertilizer.description': 'Obtenez des informations détaillées sur la santé de votre sol et des recommandations d\'engrais personnalisées pour optimiser la nutrition des cultures et maximiser les rendements.',
    'fertilizer.basicView': 'Vue de Base',
    'fertilizer.advancedView': 'Vue Avancée',
    'fertilizer.soilHealth': 'Aperçu de la Santé du Sol',
    'fertilizer.soilHealthDesc': 'Niveaux actuels de nutriments dans votre sol basés sur une analyse récente',
    'fertilizer.nitrogen': 'Azote (N)',
    'fertilizer.phosphorus': 'Phosphore (P)',
    'fertilizer.potassium': 'Potassium (K)',
    'fertilizer.high': 'Élevé',
    'fertilizer.medium': 'Moyen',
    'fertilizer.low': 'Faible',
    'fertilizer.optimal': 'Niveaux optimaux',
    'fertilizer.adequate': 'Niveaux adéquats',
    'fertilizer.needsImprovement': 'Nécessite une amélioration',
    
    // Common
    'common.required': 'est requis',
    'common.invalidEmail': 'Veuillez entrer une adresse email valide',
    'common.invalidRange': 'doit être entre',
    'common.and': 'et',
    'common.minimum': 'Minimum',
    'common.characters': 'caractères',
    'common.fixErrors': 'Veuillez corriger les erreurs du formulaire et réessayer',
    'common.loading': 'Chargement...',
    'common.success': 'Succès !',
    'common.error': 'Erreur',
    
    // Popup Translations
    // Welcome Popup
    'welcomeTitle': 'Bienvenue chez AgriSmart !',
    'welcomeSubtitle': 'Votre plateforme complète d\'intelligence agricole',
    'cropRecommendation': 'Recommandations de Cultures',
    'welcomeFeature1': 'Suggestions alimentées par IA pour une sélection optimale de cultures basée sur vos conditions',
    'weatherForecasting': 'Informations Météorologiques',
    'welcomeFeature2': 'Données météorologiques en temps réel et recommandations spécifiques à l\'agriculture',
    'soilAnalysis': 'Analyse du Sol',
    'welcomeFeature3': 'Rapports détaillés sur la santé du sol et recommandations d\'engrais',
    'getStarted': 'Commencer',
    
    // Daily Tips Popup
    'dailyTip': 'Conseil Agricole Quotidien',
    'soilHealth': 'Santé du Sol',
    'tip1Title': 'Testez Régulièrement le pH de Votre Sol',
    'tip1Content': 'Le pH du sol affecte la disponibilité des nutriments. La plupart des cultures prospèrent dans un sol légèrement acide à neutre (pH 6.0-7.0). Testez votre sol tous les 2-3 ans et ajustez avec de la chaux ou du soufre selon les besoins.',
    'waterManagement': 'Gestion de l\'Eau',
    'tip2Title': 'Implémentez l\'Irrigation Goutte à Goutte',
    'tip2Content': 'L\'irrigation goutte à goutte peut réduire l\'utilisation d\'eau de 30-50% tout en améliorant les rendements des cultures. Elle livre l\'eau directement aux racines des plantes, réduisant l\'évaporation et la croissance des mauvaises herbes.',
    'pestControl': 'Contrôle des Ravageurs',
    'tip3Title': 'Utilisez la Gestion Intégrée des Ravageurs',
    'tip3Content': 'Combinez les contrôles biologiques, culturels et chimiques pour une gestion efficace des ravageurs. Surveillez régulièrement les populations de ravageurs et utilisez des traitements ciblés pour minimiser l\'impact environnemental.',
    'previous': 'Précédent',
    'next': 'Suivant',
    
    // Location Permission Popup
    'locationPermissionTitle': 'Activer l\'Accès à la Localisation',
    'locationPermissionDescription': 'Permettez-nous d\'accéder à votre localisation pour des insights agricoles personnalisés et des données météorologiques locales.',
    'locationPrivacyNote': 'Vos données de localisation ne sont utilisées que pour fournir des recommandations localisées et ne sont jamais partagées avec des tiers.',
    'accurateWeather': 'Données Météorologiques Précises',
    'locationBenefit1': 'Obtenez des prévisions météorologiques locales précises et des alertes',
    'localConditions': 'Conditions de Culture Locales',
    'locationBenefit2': 'Recevez des recommandations adaptées à votre région spécifique',
    'nearbyResources': 'Ressources Proches',
    'locationBenefit3': 'Trouvez des fournisseurs locaux, des services de vulgarisation et des marchés',
    'skipForNow': 'Passer pour Maintenant',
    'allowLocation': 'Autoriser la Localisation',
    'locationAccessGranted': 'Accès à la localisation accordé ! Vous recevrez maintenant des recommandations locales personnalisées.',
    'locationAccessDenied': 'Accès à la localisation refusé. Vous pouvez toujours utiliser toutes les fonctionnalités avec une saisie manuelle de localisation.',
    
    // Newsletter Popup
    'newsletterTitle': 'Restez Informé',
    'newsletterDescription': 'Abonnez-vous à notre newsletter pour les dernières perspectives agricoles, conseils saisonniers et recommandations de cultures.',
    'exclusiveBenefits': 'Ce que vous recevrez :',
    'seasonalTips': 'Conseils de culture saisonniers hebdomadaires',
    'cropAlerts': 'Alertes de maladies et ravageurs des cultures',
    'expertAdvice': 'Conseils agricoles d\'experts',
    'emailPlaceholder': 'Entrez votre adresse email',
    'noThanks': 'Non Merci',
    'subscribe': 'S\'abonner',
    'subscribing': 'Abonnement...',
    'unsubscribeAnytime': 'Vous pouvez vous désabonner à tout moment. Nous respectons votre vie privée.',
    'validEmailRequired': 'Veuillez entrer une adresse email valide',
    'newsletterSubscribed': 'Abonnement à notre newsletter réussi !',
  },
  
  hi: {
    // Header
    'nav.home': 'होम',
    'nav.features': 'विशेषताएं',
    'nav.howItWorks': 'यह कैसे काम करता है',
    'nav.weather': 'मौसम',
    'nav.contact': 'संपर्क',
    'nav.tryRecommendation': 'सिफारिश आज़माएं',
    
    // Hero
    'hero.badge': 'स्मार्ट कृषि समाधान',
    'hero.title': 'अपनी फसल की',
    'hero.titleHighlight': 'उपज को अनुकूलित करें',
    'hero.subtitle': 'AI-संचालित अंतर्दृष्टि के साथ',
    'hero.description': 'अपनी मिट्टी की स्थिति, जलवायु डेटा और स्थानीय कृषि पैटर्न के आधार पर व्यक्तिगत फसल सिफारिशें प्राप्त करें। संसाधन की बर्बादी को कम करते हुए उत्पादकता को अधिकतम करें।',
    'hero.getRecommendation': 'सिफारिश प्राप्त करें',
    'hero.learnMore': 'और जानें',
    'hero.stats.varieties': 'फसल की किस्में',
    'hero.stats.accuracy': 'सटीकता दर',
    'hero.stats.farmers': 'किसानों की मदद की',
    'hero.improvement': '+32% उपज',
    'hero.improvementSub': 'औसत सुधार',
    
    // Crop Recommendation
    'crop.title': 'फसल सिफारिश प्रणाली',
    'crop.description': 'अपनी स्थानीय स्थितियों के आधार पर व्यक्तिगत फसल सिफारिशें प्राप्त करें। हमारा एल्गोरिदम मिट्टी की pH, वर्षा, तापमान और मौसमी पैटर्न का विश्लेषण करके आपके खेत के लिए सबसे उपयुक्त फसलों का सुझाव देता है।',
    'crop.formTitle': 'खेत की जानकारी',
    'crop.formDescription': 'अपने खेत का स्थान और वर्तमान खेती की स्थिति दर्ज करें',
    'crop.location': 'स्थान',
    'crop.locationPlaceholder': 'जैसे, मुंबई, महाराष्ट्र',
    'crop.soilPH': 'मिट्टी pH',
    'crop.rainfall': 'वर्षा (मिमी)',
    'crop.temperature': 'तापमान (°C)',
    'crop.season': 'मौसम',
    'crop.season.spring': 'वसंत',
    'crop.season.summer': 'गर्मी',
    'crop.season.monsoon': 'मानसून',
    'crop.season.winter': 'सर्दी',
    'crop.selectSeason': 'मौसम चुनें',
    'crop.getRecommendations': 'सिफारिशें प्राप्त करें',
    'crop.analyzing': 'विश्लेषण कर रहे हैं...',
    'crop.recommendedCrops': 'अनुशंसित फसलें',
    'crop.exportCSV': 'CSV निर्यात करें',
    'crop.fillForm': 'अपने खेत की जानकारी भरें और अपनी स्थितियों के लिए उपयुक्त फसलें देखने के लिए "सिफारिशें प्राप्त करें" पर क्लिक करें।',
    'crop.sowingMonths': 'बुआई के महीने',
    'crop.whyThisCrop': 'यह फसल क्यों',
    'crop.match': 'मैच',
    
    // Weather
    'weather.title': 'मौसम की जानकारी',
    'weather.description': 'सिंचाई, रोपण और कटाई के बारे में सूचित निर्णय लेने में मदद के लिए वास्तविक समय मौसम डेटा और कृषि-विशिष्ट अंतर्दृष्टि प्राप्त करें।',
    'weather.localWeather': 'स्थानीय मौसम',
    'weather.localWeatherDesc': 'वर्तमान मौसम की स्थिति और 5-दिन का पूर्वानुमान पाने के लिए अपना शहर दर्ज करें',
    'weather.cityPlaceholder': 'शहर का नाम दर्ज करें (जैसे, मुंबई, दिल्ली, बैंगलोर)',
    'weather.getWeather': 'मौसम प्राप्त करें',
    'weather.loading': 'लोड हो रहा है...',
    'weather.note': 'यह मॉक डेटा के साथ एक डेमो विजेट है। उत्पादन में, यह OpenWeatherMap या AccuWeather जैसे वास्तविक मौसम API के साथ एकीकृत होगा।',
    'weather.currentWeather': 'वर्तमान मौसम',
    'weather.temperature': 'तापमान',
    'weather.humidity': 'नमी',
    'weather.wind': 'किमी/घंटा हवा',
    'weather.visibility': 'किमी दृश्यता',
    'weather.farmingRecommendations': 'कृषि सिफारिशें',
    'weather.farmingRecommendationsDesc': 'आपकी कृषि गतिविधियों के लिए मौसम-आधारित सलाह',
    'weather.forecast': '5-दिन का पूर्वानुमान',
    'weather.forecastDesc': 'विस्तारित मौसम भविष्यवाणियों के साथ अपनी कृषि गतिविधियों की योजना बनाएं',
    
    // Contact
    'contact.title': 'संपर्क में रहें',
    'contact.description': 'फसल सिफारिशों के बारे में प्रश्न हैं या तकनीकी सहायता चाहिए? हम आपके कृषि संचालन को अनुकूलित करने में आपकी सहायता के लिए यहां हैं।',
    'contact.contactUs': 'हमसे संपर्क करें',
    'contact.contactUsDesc': 'नीचे दिया गया फॉर्म भरें और हम जल्द से जल्द जवाब देंगे',
    'contact.fullName': 'पूरा नाम',
    'contact.namePlaceholder': 'आपका पूरा नाम',
    'contact.emailAddress': 'ईमेल पता',
    'contact.emailPlaceholder': 'your.email@example.com',
    'contact.subject': 'विषय',
    'contact.subjectPlaceholder': 'हम आ��की कैसे मदद कर सकते हैं?',
    'contact.message': 'संदेश',
    'contact.messagePlaceholder': 'कृपया अपना प्रश्न या फीडबैक विस्तार से बताएं...',
    'contact.sendMessage': 'संदेश भेजें',
    'contact.sendingMessage': 'संदेश भेजा जा रहा है...',
    'contact.thankYou': 'धन्यवाद!',
    'contact.thankYouMessage': 'आपका संदेश सफलतापूर्वक भेजा गया है। हम 24 घंटों के भीतर आपसे संपर्क करेंगे।',
    'contact.sendAnother': 'दूसरा संदेश भेजें',
    'contact.note': 'यह एक डेमो संपर्क फॉर्म है। उत्पादन में, यह वास्तव में ईमेल भेजने या संदेशों को स्टोर करने के लिए बैकएंड सेवा के साथ एकीकृत होगा।',
    
    // FAQ
    'faq.title': 'अक्सर पूछे जाने वाले प्रश्न',
    'faq.description': 'हमारी फसल सिफारिश प्रणाली, मिट्टी विश्लेषण उपकरण और मौसम की जानकारी के बारे में सामान्य प्रश्नों के उत्तर खोजें।',
    'faq.commonQuestions': 'सामान्य प्रश्न',
    'faq.commonQuestionsDesc': 'विस्तृत उत्तर देखने के लिए नीचे किसी भी प्रश्न पर क्लिक करें',
    
    // Footer
    'footer.description': 'कृषि उत्पादकता और स्थिरता को अनुकूलित करने के लिए AI-संचालित फसल सिफारिशों, मिट्टी विश्लेषण और मौसम अंतर्दृष्टि के साथ किसानों को सशक्त बनाना।',
    'footer.quickLinks': 'त्वरित लिंक',
    'footer.features': 'विशेषताएं',
    'footer.contact': 'संपर्क',
    'footer.getSupport': 'सहायता प्राप्त करें',
    'footer.copyright': 'सभी अधिकार सुरक्षित।',
    'footer.builtWith': 'React, TypeScript, और Tailwind CSS के साथ निर्मित',
    'footer.demoNotice': 'यह एक प्रदर्शन एप्लिकेशन है जो केवल फ्रंटएंड फसल सिफारिश सुविधाओं को प्रदर्शित करता है। उत्पादन में, यह सटीक, वास्तविक समय सिफारिशों के लिए वास्तविक कृषि डेटाबेस, मौसम APIs और मशीन लर्निंग मॉडल के साथ एकीकृत होगा।',
    
    // How It Works
    'howItWorks.title': 'यह कैसे काम करता है',
    'howItWorks.description': 'हमारी बुद्धिमान फसल सिफारिश प्रणाली आपकी विशिष्ट कृषि स्थितियों के लिए सबसे उपयुक्त फसलों का सुझाव देने के लिए डेटा-संचालित दृष्टिकोण का उपयोग करती है।',
    'howItWorks.step': 'चरण',
    'howItWorks.learnMore': 'और जानें',
    'howItWorks.inputDetails': 'खेत की जानकारी दर्ज करें',
    'howItWorks.inputDetailsDesc': 'अपना स्थान और वर्तमान खेती की स्थिति प्रदान करें',
    'howItWorks.algorithmAnalysis': 'एल्गोरिदम विश्लेषण',
    'howItWorks.algorithmAnalysisDesc': 'हमारी प्रणाली फसल आवश्यकताओं के विरुद्ध आपके डेटा का विश्लेषण करती है',
    'howItWorks.scoring': 'स्कोरिंग और रैंकिंग',
    'howItWorks.scoringDesc': 'फसलों को उपयुक्तता के आधार पर स्कोर और रैंक किया जाता है',
    'howItWorks.getRecommendations': 'सिफारिशें प्राप्त करें',
    'howItWorks.getRecommendationsDesc': 'विश्वास स्कोर के साथ व्यक्तिगत फसल सुझाव प्राप्त करें',
    
    // Fertilizer
    'fertilizer.title': 'मिट्टी विश्लेषण और उर्वरक सिफारिशें',
    'fertilizer.description': 'फसल पोषण को अनुकूलित करने और उपज को अधिकतम करने के लिए अपनी मिट्टी के स्वास्थ्य में विस्तृत अंतर्दृष्टि और व्यक्तिगत उर्वरक सिफारिशें प्राप्त करें।',
    'fertilizer.basicView': 'बुनियादी दृश्य',
    'fertilizer.advancedView': 'उन्नत दृश्य',
    'fertilizer.soilHealth': 'मिट्टी स्वास्थ्य अवलोकन',
    'fertilizer.soilHealthDesc': 'हाल के विश्लेषण के आधार पर आपकी मिट्टी में वर्तमान पोषक तत्व स्तर',
    'fertilizer.nitrogen': 'नाइट्रोजन (N)',
    'fertilizer.phosphorus': 'फास्फोरस (P)',
    'fertilizer.potassium': 'पोटेशियम (K)',
    'fertilizer.high': 'उच्च',
    'fertilizer.medium': 'मध्यम',
    'fertilizer.low': 'कम',
    'fertilizer.optimal': 'इष्टतम स्तर',
    'fertilizer.adequate': 'पर्याप्त स्तर',
    'fertilizer.needsImprovement': 'सुधार की आवश्यकता',
    
    // Common
    'common.required': 'आवश्यक है',
    'common.invalidEmail': 'कृपया एक वैध ईमेल पता दर्ज करें',
    'common.invalidRange': 'के बीच होना चाहिए',
    'common.and': 'और',
    'common.minimum': 'न्यूनतम',
    'common.characters': 'वर्ण',
    'common.fixErrors': 'कृपया फॉर्म त्रुटियों को ठीक करें और पु��ः प्रयास करें',
    'common.loading': 'लोड हो रहा है...',
    'common.success': 'सफलता!',
    'common.error': 'त्रुटि',
    
    // Popup Translations
    // Welcome Popup
    'welcomeTitle': 'AgriSmart में आपका स्वागत है!',
    'welcomeSubtitle': 'आपका व्यापक कृषि बुद्धिमत्ता मंच',
    'cropRecommendation': 'फसल सिफारिशें',
    'welcomeFeature1': 'आपकी स्थितियों के आधार पर इष्टतम फसल चयन के लिए AI-संचालित सुझाव',
    'weatherForecasting': 'मौसम की जानकारी',
    'welcomeFeature2': 'वास्तविक समय मौसम डेटा और कृषि-विशिष्ट सिफारिशें',
    'soilAnalysis': 'मिट्टी विश्लेषण',
    'welcomeFeature3': 'विस्तृत मिट्टी स्वास्थ्य रिपोर्ट और उर्वरक सिफारिशें',
    'getStarted': 'शुरू करें',
    
    // Daily Tips Popup
    'dailyTip': 'दैनिक कृषि सुझाव',
    'soilHealth': 'मिट्टी का स्वास्थ्य',
    'tip1Title': 'अपनी मिट्टी का pH नियमित रूप से जांचें',
    'tip1Content': 'मिट्टी का pH पोषक तत्वों की उपलब्धता को प्रभावित करता है। अधिकांश फसलें थोड़ी अम्लीय से तटस्थ मिट्टी (pH 6.0-7.0) में अच्छी तरह पनपती हैं। हर 2-3 साल में अपनी मिट्टी का परीक्षण करें और आवश्यकतानुसार चूना या गंधक से समायोजित करें।',
    'waterManagement': 'जल प्रबंधन',
    'tip2Title': 'ड्रिप सिंचाई लागू करें',
    'tip2Content': 'ड्रिप सिंचाई पानी के उपयोग को 30-50% तक कम कर सकती है और फसल की पैदावार में सुधार कर सकती है। यह पानी को सीधे पौधों की जड़ों तक पहुंचाती है, वाष्पीकरण और खरपतवार की वृद्धि को कम करती है।',
    'pestControl': 'कीट नियंत्रण',
    'tip3Title': 'एकीकृत कीट प्रबंधन का उपयोग करें',
    'tip3Content': 'प्रभावी कीट प्रबंधन के लिए जैविक, सांस्कृतिक और रासायनिक नियंत्रण को मिलाएं। कीट आबादी की नियमित निगरानी करें और पर्यावरणीय प्रभाव को कम करने के लिए लक्षित उपचार का उपयोग करें।',
    'previous': 'पिछला',
    'next': 'अगला',
    
    // Location Permission Popup
    'locationPermissionTitle': 'स्थान पहुंच सक्षम करें',
    'locationPermissionDescription': 'व्यक्तिगत कृषि अंतर्दृष्टि और स्थानीय मौसम डेटा के लिए हमें अपने स्थान तक पहुंचने की अनुमति दें।',
    'locationPrivacyNote': 'आपके स्थान का डेटा केवल स्थानीयकृत सिफारिशें प्रदान करने के लिए उपयोग किया जाता है और कभी भी तीसरे पक्ष के साथ साझा नहीं किया जाता।',
    'accurateWeather': 'सटीक मौसम डेटा',
    'locationBenefit1': 'सटीक स्थानीय मौसम पूर्वानुमान और अलर्ट प्राप्त करें',
    'localConditions': 'स्थानीय उगाने की स्थितियां',
    'locationBenefit2': 'अपने विशिष्ट क्षेत्र के अनुकूल सिफारिशें प्राप्त करें',
    'nearbyResources': 'पास के संसाधन',
    'locationBenefit3': 'स्थानीय आपूर्तिकर्ता, विस्तार सेवाएं और बाजार खोजें',
    'skipForNow': 'अभी छोड़ें',
    'allowLocation': 'स्थान की अनुमति दें',
    'locationAccessGranted': 'स्थान पहुंच की अनुमति मिल गई! अब आप व्यक्तिगत स्थानीय सिफारिशें प्राप्त करेंगे।',
    'locationAccessDenied': 'स्थान पहुंच से इनकार कर दिया गया। आप अभी भी मैन्युअल स्थान प्रविष्टि के साथ सभी सुविधाओं का उपयोग कर सकते हैं।',
    
    // Newsletter Popup
    'newsletterTitle': 'अपडेट रहें',
    'newsletterDescription': 'नवीनतम कृषि अंतर्दृष्टि, मौसमी सुझाव और फसल सिफारिशों के लिए हमारे न्यूज़लेटर की सदस्यता लें।',
    'exclusiveBenefits': 'आपको क्या मिलेगा:',
    'seasonalTips': 'साप्ताहिक मौसमी खेती के सुझाव',
    'cropAlerts': 'फसल रोग और कीट अलर्ट',
    'expertAdvice': 'विशेषज्ञ कृषि सलाह',
    'emailPlaceholder': 'अपना ईमेल पता दर्ज करें',
    'noThanks': 'नहीं धन्यवाद',
    'subscribe': 'सदस्यता लें',
    'subscribing': 'सदस्यता ले रहे हैं...',
    'unsubscribeAnytime': 'आप किसी भी समय सदस्यता रद्द कर सकते हैं। हम आपकी गोपनीयता का सम्मान करते हैं।',
    'validEmailRequired': 'कृपया एक वैध ईमेल पता दर्ज करें',
    'newsletterSubscribed': 'हमारे न्यूज़लेटर की सफलतापूर्वक सदस्यता ली गई!',
  },
  
  pt: {
    // Header
    'nav.home': 'Início',
    'nav.features': 'Recursos',
    'nav.howItWorks': 'Como funciona',
    'nav.weather': 'Clima',
    'nav.contact': 'Contato',
    'nav.tryRecommendation': 'Experimentar Recomendação',
    
    // Hero
    'hero.badge': 'Soluções de Agricultura Inteligente',
    'hero.title': 'Otimize seus',
    'hero.titleHighlight': 'Rendimentos de Culturas',
    'hero.subtitle': 'com Insights Alimentados por IA',
    'hero.description': 'Obtenha recomendações personalizadas de culturas baseadas nas condições do seu solo, dados climáticos e padrões agrícolas locais. Maximize a produtividade enquanto minimiza o desperdício de recursos.',
    'hero.getRecommendation': 'Obter Recomendação',
    'hero.learnMore': 'Saiba Mais',
    'hero.stats.varieties': 'Variedades de Culturas',
    'hero.stats.accuracy': 'Taxa de Precisão',
    'hero.stats.farmers': 'Agricultores Ajudados',
    'hero.improvement': '+32% Rendimento',
    'hero.improvementSub': 'Melhoria Média',
    
    // Crop Recommendation
    'crop.title': 'Sistema de Recomendação de Culturas',
    'crop.description': 'Obtenha recomendações personalizadas de culturas baseadas nas suas condições locais. Nosso algoritmo analisa o pH do solo, chuva, temperatura e padrões sazonais para sugerir as culturas mais adequadas para sua fazenda.',
    'crop.formTitle': 'Detalhes da Fazenda',
    'crop.formDescription': 'Digite a localização da sua fazenda e as condições de cultivo atuais',
    'crop.location': 'Localização',
    'crop.locationPlaceholder': 'ex., São Paulo, Brasil',
    'crop.soilPH': 'pH do Solo',
    'crop.rainfall': 'Precipitação (mm)',
    'crop.temperature': 'Temperatura (°C)',
    'crop.season': 'Estação',
    'crop.season.spring': 'Primavera',
    'crop.season.summer': 'Verão',
    'crop.season.monsoon': 'Monção',
    'crop.season.winter': 'Inverno',
    'crop.selectSeason': 'Selecionar estação',
    'crop.getRecommendations': 'Obter Recomendações',
    'crop.analyzing': 'Analisando...',
    'crop.recommendedCrops': 'Culturas Recomendadas',
    'crop.exportCSV': 'Exportar CSV',
    'crop.fillForm': 'Preencha os detalhes da sua fazenda e clique em "Obter Recomendações" para ver culturas adequadas às suas condições.',
    'crop.sowingMonths': 'Meses de Plantio',
    'crop.whyThisCrop': 'Por que esta cultura',
    'crop.match': 'Correspondência',
    
    // Weather
    'weather.title': 'Informações Meteorológicas',
    'weather.description': 'Obtenha dados meteorológicos em tempo real e insights específicos para agricultura para ajudá-lo a tomar decisões informadas sobre irrigação, plantio e colheita.',
    'weather.localWeather': 'Clima Local',
    'weather.localWeatherDesc': 'Digite sua cidade para obter as condições meteorológicas atuais e previsão de 5 dias',
    'weather.cityPlaceholder': 'Digite o nome da cidade (ex., São Paulo, Rio de Janeiro, Brasília)',
    'weather.getWeather': 'Obter Clima',
    'weather.loading': 'Carregando...',
    'weather.note': 'Este é um widget de demonstração com dados simulados. Em produção, isso se integraria com uma API meteorológica real como OpenWeatherMap ou AccuWeather.',
    'weather.currentWeather': 'Clima Atual',
    'weather.temperature': 'Temperatura',
    'weather.humidity': 'Umidade',
    'weather.wind': 'km/h Vento',
    'weather.visibility': 'km Visibilidade',
    'weather.farmingRecommendations': 'Recomendações Agrícolas',
    'weather.farmingRecommendationsDesc': 'Conselhos baseados no clima para suas atividades agrícolas',
    'weather.forecast': 'Previsão de 5 Dias',
    'weather.forecastDesc': 'Planeje suas atividades agrícolas com previsões meteorológicas estendidas',
    
    // Contact
    'contact.title': 'Entre em Contato',
    'contact.description': 'Tem dúvidas sobre recomendações de culturas ou precisa de suporte técnico? Estamos aqui para ajudá-lo a otimizar suas operações agrícolas.',
    'contact.contactUs': 'Fale Conosco',
    'contact.contactUsDesc': 'Preencha o formulário abaixo e responderemos o mais rápido possível',
    'contact.fullName': 'Nome Completo',
    'contact.namePlaceholder': 'Seu nome completo',
    'contact.emailAddress': 'Endereço de Email',
    'contact.emailPlaceholder': 'seu.email@exemplo.com',
    'contact.subject': 'Assunto',
    'contact.subjectPlaceholder': 'Como podemos ajudá-lo?',
    'contact.message': 'Mensagem',
    'contact.messagePlaceholder': 'Por favor, descreva sua pergunta ou comentário em detalhes...',
    'contact.sendMessage': 'Enviar Mensagem',
    'contact.sendingMessage': 'Enviando Mensagem...',
    'contact.thankYou': 'Obrigado!',
    'contact.thankYouMessage': 'Sua mensagem foi enviada com sucesso. Responderemos dentro de 24 horas.',
    'contact.sendAnother': 'Enviar Outra Mensagem',
    'contact.note': 'Este é um formulário de contato de demonstração. Em produção, isso se integraria com um serviço backend para enviar emails ou armazenar mensagens.',
    
    // FAQ
    'faq.title': 'Perguntas Frequentes',
    'faq.description': 'Encontre respostas para perguntas comuns sobre nosso sistema de recomendação de culturas, ferramentas de análise do solo e informações meteorológicas.',
    'faq.commonQuestions': 'Perguntas Comuns',
    'faq.commonQuestionsDesc': 'Clique em qualquer pergunta abaixo para ver a resposta detalhada',
    
    // Footer
    'footer.description': 'Capacitando agricultores com recomendações de culturas alimentadas por IA, análise do solo e insights meteorológicos para otimizar a produtividade e sustentabilidade agrícola.',
    'footer.quickLinks': 'Links Rápidos',
    'footer.features': 'Recursos',
    'footer.contact': 'Contato',
    'footer.getSupport': 'Obter Suporte',
    'footer.copyright': 'Todos os direitos reservados.',
    'footer.builtWith': 'Construído com React, TypeScript e Tailwind CSS',
    'footer.demoNotice': 'Esta é uma aplicação de demonstração apresentando recursos de recomendação de culturas apenas frontend. Em produção, isso se integraria com bancos de dados agrícolas reais, APIs meteorológicas e modelos de aprendizado de máquina para recomendações precisas e em tempo real.',
    
    // How It Works
    'howItWorks.title': 'Como Funciona',
    'howItWorks.description': 'Nosso sistema inteligente de recomendação de culturas usa uma abordagem baseada em dados para sugerir as culturas mais adequadas para suas condições agrícolas específicas.',
    'howItWorks.step': 'Passo',
    'howItWorks.learnMore': 'Saiba Mais',
    'howItWorks.inputDetails': 'Inserir Detalhes da Fazenda',
    'howItWorks.inputDetailsDesc': 'Forneça sua localização e condições de cultivo atuais',
    'howItWorks.algorithmAnalysis': 'Análise do Algoritmo',
    'howItWorks.algorithmAnalysisDesc': 'Nosso sistema analisa seus dados contra os requisitos das culturas',
    'howItWorks.scoring': 'Pontuação e Classificação',
    'howItWorks.scoringDesc': 'As culturas são pontuadas e classificadas com base na adequação',
    'howItWorks.getRecommendations': 'Obter Recomendações',
    'howItWorks.getRecommendationsDesc': 'Receba sugestões personalizadas de culturas com pontuações de confiança',
    
    // Fertilizer
    'fertilizer.title': 'Análise do Solo e Recomendações de Fertilizantes',
    'fertilizer.description': 'Obtenha insights detalhados sobre a saúde do seu solo e recomendações personalizadas de fertilizantes para otimizar a nutrição das culturas e maximizar os rendimentos.',
    'fertilizer.basicView': 'Visualização Básica',
    'fertilizer.advancedView': 'Visualização Avançada',
    'fertilizer.soilHealth': 'Visão Geral da Saúde do Solo',
    'fertilizer.soilHealthDesc': 'Níveis atuais de nutrientes no seu solo baseados em análise recente',
    'fertilizer.nitrogen': 'Nitrogênio (N)',
    'fertilizer.phosphorus': 'Fósforo (P)',
    'fertilizer.potassium': 'Potássio (K)',
    'fertilizer.high': 'Alto',
    'fertilizer.medium': 'Médio',
    'fertilizer.low': 'Baixo',
    'fertilizer.optimal': 'Níveis ótimos',
    'fertilizer.adequate': 'Níveis adequados',
    'fertilizer.needsImprovement': 'Precisa de melhoria',
    
    // Common
    'common.required': 'é obrigatório',
    'common.invalidEmail': 'Por favor, digite um endereço de email válido',
    'common.invalidRange': 'deve estar entre',
    'common.and': 'e',
    'common.minimum': 'Mínimo',
    'common.characters': 'caracteres',
    'common.fixErrors': 'Por favor, corrija os erros do formulário e tente novamente',
    'common.loading': 'Carregando...',
    'common.success': 'Sucesso!',
    'common.error': 'Erro',
    
    // Popup Translations
    // Welcome Popup
    'welcomeTitle': 'Bem-vindo ao AgriSmart!',
    'welcomeSubtitle': 'Sua plataforma abrangente de inteligência agrícola',
    'cropRecommendation': 'Recomendações de Culturas',
    'welcomeFeature1': 'Sugestões baseadas em IA para seleção ótima de culturas com base nas suas condições',
    'weatherForecasting': 'Informações Meteorológicas',
    'welcomeFeature2': 'Dados meteorológicos em tempo real e recomendações específicas para agricultura',
    'soilAnalysis': 'Análise do Solo',
    'welcomeFeature3': 'Relatórios detalhados de saúde do solo e recomendações de fertilizantes',
    'getStarted': 'Começar',
    
    // Daily Tips Popup
    'dailyTip': 'Dica Agrícola Diária',
    'soilHealth': 'Saúde do Solo',
    'tip1Title': 'Teste o pH do Seu Solo Regularmente',
    'tip1Content': 'O pH do solo afeta a disponibilidade de nutrientes. A maioria das culturas prospera em solo ligeiramente ácido a neutro (pH 6.0-7.0). Teste seu solo a cada 2-3 anos e ajuste com calcário ou enxofre conforme necessário.',
    'waterManagement': 'Gestão da Água',
    'tip2Title': 'Implemente Irrigação por Gotejamento',
    'tip2Content': 'A irrigação por gotejamento pode reduzir o uso de água em 30-50% enquanto melhora os rendimentos das culturas. Ela fornece água diretamente às raízes das plantas, reduzindo a evaporação e o crescimento de ervas daninhas.',
    'pestControl': 'Controle de Pragas',
    'tip3Title': 'Use Manejo Integrado de Pragas',
    'tip3Content': 'Combine controles biológicos, culturais e químicos para manejo eficaz de pragas. Monitore as populações de pragas regularmente e use tratamentos direcionados para minimizar o impacto ambiental.',
    'previous': 'Anterior',
    'next': 'Próximo',
    
    // Location Permission Popup
    'locationPermissionTitle': 'Habilitar Acesso à Localização',
    'locationPermissionDescription': 'Permita-nos acessar sua localização para insights agrícolas personalizados e dados meteorológicos locais.',
    'locationPrivacyNote': 'Seus dados de localização são usados apenas para fornecer recomendações localizadas e nunca são compartilhados com terceiros.',
    'accurateWeather': 'Dados Meteorológicos Precisos',
    'locationBenefit1': 'Obtenha previsões meteorológicas locais precisas e alertas',
    'localConditions': 'Condições de Cultivo Locais',
    'locationBenefit2': 'Receba recomendações adaptadas à sua região específica',
    'nearbyResources': 'Recursos Próximos',
    'locationBenefit3': 'Encontre fornecedores locais, serviços de extensão e mercados',
    'skipForNow': 'Pular por Enquanto',
    'allowLocation': 'Permitir Localização',
    'locationAccessGranted': 'Acesso à localização concedido! Agora você receberá recomendações locais personalizadas.',
    'locationAccessDenied': 'Acesso à localização negado. Você ainda pode usar todos os recursos com entrada manual de localização.',
    
    // Newsletter Popup
    'newsletterTitle': 'Mantenha-se Atualizado',
    'newsletterDescription': 'Inscreva-se em nossa newsletter para os mais recentes insights agrícolas, dicas sazonais e recomendações de culturas.',
    'exclusiveBenefits': 'O que você receberá:',
    'seasonalTips': 'Dicas semanais de cultivo sazonal',
    'cropAlerts': 'Alertas de doenças e pragas das culturas',
    'expertAdvice': 'Conselhos agrícolas especializados',
    'emailPlaceholder': 'Digite seu endereço de email',
    'noThanks': 'Não Obrigado',
    'subscribe': 'Inscrever-se',
    'subscribing': 'Inscrevendo...',
    'unsubscribeAnytime': 'Você pode cancelar a inscrição a qualquer momento. Respeitamos sua privacidade.',
    'validEmailRequired': 'Por favor, digite um endereço de email válido',
    'newsletterSubscribed': 'Inscrito com sucesso em nossa newsletter!',
  },
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    const browserLanguage = navigator.language.split('-')[0] as Language;
    
    if (savedLanguage && translations[savedLanguage]) {
      setLanguageState(savedLanguage);
    } else if (translations[browserLanguage]) {
      setLanguageState(browserLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};